# Generated by Django 5.2.3 on 2025-09-18 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paralympic2050', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='athletes',
            table='athletes',
        ),
    ]
