# Generated by Django 5.2.3 on 2025-09-21 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paralympic2050', '0002_alter_athletes_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterModelOptions(
            name='athletes',
            options={'verbose_name': 'Athlete', 'verbose_name_plural': 'Athletes'},
        ),
    ]
