# Generated by Django 5.2.3 on 2025-09-21 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paralympic2050', '0003_userdata_alter_athletes_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdata',
            options={'verbose_name': 'userdata', 'verbose_name_plural': 'userdatas'},
        ),
        migrations.AlterModelTable(
            name='userdata',
            table='userdatas',
        ),
    ]
