# Generated by Django 5.2.3 on 2025-10-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paralympic2050', '0004_alter_userdata_options_alter_userdata_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='athletes',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
