# Generated by Django 5.2.3 on 2025-10-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paralympic2050', '0005_athletes_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athletes',
            name='bid',
            field=models.IntegerField(max_length=5),
        ),
    ]
