# Generated by Django 5.2.3 on 2025-10-04 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paralympic2050', '0007_alter_athletes_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athletes',
            name='country',
            field=models.CharField(max_length=100),
        ),
    ]
