# Generated by Django 5.2.3 on 2025-10-13 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paralympic2050', '0008_alter_athletes_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Date and Time')),
                ('number', models.CharField(max_length=10, verbose_name='Event No.')),
                ('gender', models.CharField(max_length=10)),
                ('sport', models.CharField(max_length=100)),
                ('classification', models.CharField(max_length=10)),
                ('phrase', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date_time'],
            },
        ),
    ]
