# Generated by Django 5.2.3 on 2025-10-13 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paralympic2050', '0009_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date_time'], 'verbose_name': 'sport_event', 'verbose_name_plural': 'sport_events'},
        ),
        migrations.AlterModelTable(
            name='event',
            table='sport_events',
        ),
    ]
