# Generated by Django 5.2.3 on 2025-10-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paralympic2050', '0011_event_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=100)),
                ('gold', models.PositiveIntegerField(default=0)),
                ('silver', models.PositiveIntegerField(default=0)),
                ('bronze', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'medal',
                'verbose_name_plural': 'medals',
                'db_table': 'medal_summary',
            },
        ),
    ]
