# Generated by Django 5.2.3 on 2025-10-28 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paralympic2050', '0012_medal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('A', 'Category A'), ('B', 'Category B')], max_length=1)),
                ('ticket_type', models.CharField(choices=[('standard', 'Full Price - Standard'), ('disability', 'Full Price - with disability/impairment'), ('companion', 'Reduced Price - Companion'), ('under14', 'Reduced Price - Under 14'), ('under14_disability', 'Reduced Price - Under 14 with disability/impairment')], max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='Paralympic2050.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='Paralympic2050.userdata')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'tickets',
            },
        ),
    ]
