# Generated by Django 5.2.3 on 2025-10-28 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paralympic2050', '0013_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='booked_at',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paralympic2050.event'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='total_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Paralympic2050.userdata'),
        ),
    ]
