# Generated by Django 5.2.3 on 2025-10-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paralympic2050', '0014_rename_booked_at_ticket_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={},
        ),
        migrations.AddField(
            model_name='ticket',
            name='visa_last_four',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('A', 'Category A'), ('B', 'Category B')], max_length=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterModelTable(
            name='ticket',
            table=None,
        ),
    ]
