# Generated by Django 5.2.3 on 2025-10-28 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Paralympic2050', '0015_alter_ticket_options_ticket_visa_last_four_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'tickets', 'verbose_name_plural': 'ticket_value'},
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='ticket',
        ),
    ]
